from ct2hf.compute_type import ComputeType

class Arguments:
    @property
    def model_id(self) -> str: ...
    @property
    def output_name(self) -> str | None: ...
    @property
    def revision(self) -> str | None: ...
    @property
    def files_to_copy(self) -> list[str]: ...
    @property
    def preserve_models(self) -> bool: ...
    @property
    def compatibility(self) -> bool: ...
    @property
    def quantisation(self) -> ComputeType | None: ...

def parse_args() -> Arguments: ...
