name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - pyproject.toml
      - uv.lock
      - ct2hf/**

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-python.yml@main
